/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PayRouteImport } from './routes/pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as FacultyFacultyIdRouteImport } from './routes/faculty.$facultyId'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyFacultyIdRoute = FacultyFacultyIdRouteImport.update({
  id: '/faculty/$facultyId',
  path: '/faculty/$facultyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/leaves': typeof LeavesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/update-password': typeof UpdatePasswordRoute
  '/users': typeof UsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/leaves': typeof LeavesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/update-password': typeof UpdatePasswordRoute
  '/users': typeof UsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/exams': typeof ExamsIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/leaves': typeof LeavesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/update-password': typeof UpdatePasswordRoute
  '/users': typeof UsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit'
    | '/courses'
    | '/dashboard'
    | '/fees'
    | '/leaves'
    | '/library'
    | '/login'
    | '/pay'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/update-password'
    | '/users'
    | '/exams/$examId'
    | '/faculty/$facultyId'
    | '/students/$studentId'
    | '/exams/'
    | '/faculty/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit'
    | '/courses'
    | '/dashboard'
    | '/fees'
    | '/leaves'
    | '/library'
    | '/login'
    | '/pay'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/update-password'
    | '/users'
    | '/exams/$examId'
    | '/faculty/$facultyId'
    | '/students/$studentId'
    | '/exams'
    | '/faculty'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit'
    | '/courses'
    | '/dashboard'
    | '/fees'
    | '/leaves'
    | '/library'
    | '/login'
    | '/pay'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/update-password'
    | '/users'
    | '/exams/$examId'
    | '/faculty/$facultyId'
    | '/students/$studentId'
    | '/exams/'
    | '/faculty/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  FeesRoute: typeof FeesRoute
  LeavesRoute: typeof LeavesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  PayrollRoute: typeof PayrollRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TimetableRoute: typeof TimetableRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  UsersRoute: typeof UsersRoute
  ExamsExamIdRoute: typeof ExamsExamIdRoute
  FacultyFacultyIdRoute: typeof FacultyFacultyIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$facultyId': {
      id: '/faculty/$facultyId'
      path: '/faculty/$facultyId'
      fullPath: '/faculty/$facultyId'
      preLoaderRoute: typeof FacultyFacultyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  FeesRoute: FeesRoute,
  LeavesRoute: LeavesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  PayrollRoute: PayrollRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TimetableRoute: TimetableRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  UsersRoute: UsersRoute,
  ExamsExamIdRoute: ExamsExamIdRoute,
  FacultyFacultyIdRoute: FacultyFacultyIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
